name: ImageNet::Moth
description: "Test Conv2dMoth Layer on ImageNet Dataset"
hyperparameters:
  global_batch_size: 512
  lr:
    type: log
    minval: -5.0
    maxval: -1.0
    base: 10
  weight_decay:
    type: log
    minval: -7.0
    maxval: -2.0
    base: 10
  activation_func:
    type: categorical
    vals: [normal, moth]
searcher:
  name: adaptive_asha
  metric: loss
  max_length:
    epochs: 5
  max_trials: 500
  smaller_is_better: true
records_per_epoch: 1281167
min_validation_period:
  records: 100000
workspace: "ML-Testcase"
project: MothLayer
entrypoint: determined_ai.moth_image_net:MothTrial
environment:
  image:
    cpu: "determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-0.26.4"
    cuda: "determinedai/pytorch-ngc:0.38.0"
bind_mounts:
  - host_path: "/home/alok/misc/data"
    container_path: "/data"
    read_only: true
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 0
  save_experiment_best: 0
max_restarts: 0
