name: ImageNet::Moth
description: "SuppressionLayer v3 - no weight decay"
hyperparameters:
  global_batch_size: 512
  lr: 0.01
  weight_decay: 0.0000
  activation_func: normal
  momentum: 0.9
  use_suppression: true
searcher:
  name: single
  metric: loss
  max_length:
    epochs: 11
  smaller_is_better: true
records_per_epoch: 1281167
min_validation_period:
  batches: 1024
workspace: "ML-Testcase"
project: MothLayer
entrypoint: determined_ai.trials_image_net:MothTrial
environment:
  image:
    cpu: "determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-0.26.4"
    cuda: "bruno1996/determined-pytorch:0.1"
bind_mounts:
  - host_path: "/home/alok/data"
    container_path: "/data"
    read_only: true
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 0
  save_experiment_best: 0
max_restarts: 0
